<h1> Import numpy</h1>

In [1]:
import numpy as np

<h1>Basic Array Methods</h1>
<p> The NumPy array class is ndarray , which consists of a multidimensional table of elements indexed by a tuple of integers </p>
<h2>Creating an Array</h2>

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
b = np.array((2,3,4))
b

array([2, 3, 4])

In [8]:
np.empty([2,2])

array([[2.54846267e+161, 1.33166785e+179],
       [9.08367229e+223, 7.01413727e-009]])

<h3>There are also helper methods, np.zeros and np.ones , which create an array of the
specified shape with elements prefilled with 0 and 1, respectively. np.empty , np.zeros
and np.ones also take the optional dtype argument </h3>

In [10]:
 np.zeros((3,2)) # default dtype is ' float '

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
 np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

<h1>Initializing an Array from a Sequence</h1>

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(2,10,2)
b

array([2, 4, 6, 8])

 <h4> np.linspace(inicio, fin, cantidad elemtos) </h4>
 
 dx = np.linspace(1, 20, 5)
 
 dx = (end-start)/(num-1)
  

In [19]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

<h1>Initializing an Array from a Function </h1>

In [20]:
 def f(i, j):
    return 2 * i * j

In [23]:
np.fromfunction(f,(3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  4.,  8., 12., 16.]])

In [24]:
 a.shape

(10,)

<h1>Universal Functions ( ufuncs)</h1>
<p> Universal functions that act on each element of an array, producing an array in return without the need for an explicit loop. Universal functions are the way NumPy allows for vectorization, which promotes clean, efficient and easy-to-maintain code </p>

In [28]:
 x = np.linspace(1, 5, 5)
x

array([1., 2., 3., 4., 5.])

In [33]:
 x**2

array([ 1.,  4.,  9., 16., 25.])

In [49]:
a1 = np.array( ((1, 2), (3, 4)) )
a1 = b
a1 * b   #elementwise multiplication

array([ 4, 16, 36, 64])

In [41]:
a.dot(b) # matrix multiplication; also a.dot(b) or np.dot(a, b)

120

In [50]:
a = np.linspace(1, 6, 6)**3

In [51]:
 print(a)

[  1.   8.  27.  64. 125. 216.]


In [52]:
print(a > 100)

[False False False False  True  True]


In [53]:
 print((a < 10) | (a > 100))

[ True  True False False  True  True]
