In [2]:
import numpy as np

In [55]:
# Create array from 0 to 9
a = np.arange(10)
print(a)
b = np.arange(2,500,25)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[  2  27  52  77 102 127 152 177 202 227 252 277 302 327 352 377 402 427
 452 477]


In [15]:
# Create Array Numpy
other = np.array([1,23,56,90,45,23,678,1,3])
other

array([  1,  23,  56,  90,  45,  23, 678,   1,   3])

In [16]:
# Get five item
other[6]

678

In [13]:
# Get items from pos 2 to 4 excluded
other[2:4]

array([56, 90])

In [17]:
# Get items from pos 2 to final with salt 3
other[2::3]

array([56, 23,  3])

In [20]:
# GET TYPE
type(other)

numpy.ndarray

In [24]:
# Create array with 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
# Create array with 1
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# linspace (inicio intervalo, fin de intervalo, cantidad de elementos)
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [43]:
# Create array with 2 dimensions
two_dimensions = np.array([[],[]])
two_dimensions

array([], shape=(2, 0), dtype=float64)

In [41]:
two_dimensions = np.array([[1,2,3,],['y','x','z']])
two_dimensions

array([['1', '2', '3'],
       ['y', 'x', 'z']], dtype='<U11')

In [44]:
# Know dimensions
two_dimensions.ndim

2

In [51]:
#Using Methods
other = np.array([1,23,56,90,45,23,678,1,3])
np.sort(other)

array([  1,   1,   3,  23,  23,  45,  56,  90, 678])